version: '3.9'
services:
  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  redis-ui:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
  ws:
    build: 
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    volumes:
      - ./ws:/code
    environment:
      - FLASK_APP=ws.py
      - FLASK_DEBUG=1
    command: "flask run --host=0.0.0.0"
  fe:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /fe
    volumes:
      - ./frontend:/fe
    ports:
      - 9999:9876
    command: "npm run dev -- --host"
    tty: true