version: '3.9'
services:
  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root1234
      ME_CONFIG_MONGODB_URL: mongodb://root:root1234@mongo:27017/

  redis-ui:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
  ws:
    build: 
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    volumes:
      - ./ws:/code
    environment:
      - FLASK_APP=ws.py
      - FLASK_DEBUG=1
    command: "flask run --host=0.0.0.0"
    depends_on:
      - mongo
  fe:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /fe
    volumes:
      - ./frontend/vite.config.js:/fe/vite.config.js
      - ./frontend/svelte.config.js:/fe/svelte.config.js
      - ./frontend/tailwind.config.cjs:/fe/tailwind.config.cjs
      - ./frontend/postcss.config.cjs:/fe/postcss.config.cjs
      - ./frontend/index.html:/fe/index.html
      - ./frontend/src:/fe/src
      - ./frontend/public:/fe/public
      - ./frontend/static:/fe/static
    ports:
      - 9999:9876
    command: "npm run dev -- --host"
    tty: true
    depends_on:
      - ws